# Generated by Django 4.2.1 on 2023-06-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_scraper', '0002_remove_doctor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(default='noname', max_length=255),
            preserve_default=False,
        ),
    ]
