# Generated by Django 4.2.1 on 2023-06-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_scraper', '0003_doctor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_photos/'),
        ),
    ]
