# Generated by Django 4.2.1 on 2023-06-08 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_scraper', '0005_cv_services_doctor_phone_doctor_cv_doctor_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='doctor',
        ),
        migrations.AddField(
            model_name='doctor',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor_scraper.review'),
        ),
    ]
