# Generated by Django 4.2.1 on 2023-06-08 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_scraper', '0006_remove_review_doctor_doctor_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctor_scraper.doctor'),
            preserve_default=False,
        ),
    ]
