# Generated by Django 4.2.1 on 2023-06-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_scraper', '0008_doctor_email_doctor_sub_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
