# Generated by Django 4.2.1 on 2023-06-09 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_scraper', '0012_remove_doctor_services_doctor_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='awards',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='education',
            new_name='educations',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='experience',
            new_name='interests',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='publications',
            new_name='languages',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='languages_spoken',
        ),
    ]
