# Generated by Django 4.2.1 on 2023-06-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_scraper', '0013_rename_awards_cv_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
