# Generated by Django 4.2.2 on 2023-06-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_scraper', '0014_alter_doctor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.TextField(default='00:00'),
        ),
    ]
